# Generated by Django 6.0.6 on 2026-07-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='🏆', help_text='emoji badge', max_length=8)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=10)),
                ('metric', models.CharField(choices=[('login_streak', 'Login streak (consecutive days)'), ('tasks_done', 'Tasks completed'), ('tasks_failed', 'Tasks failed'), ('cat_happiness', 'Cat happiness reached (%)'), ('cat_satiety', 'Cat fullness reached (%)'), ('items_bought_total', 'Items bought (total)'), ('items_bought_category', 'Items bought (category)'), ('items_bought_item', 'Items bought (specific item)')], max_length=24)),
                ('threshold', models.PositiveIntegerField(help_text='Target value: streak days, a count, or a percentage.')),
                ('category', models.CharField(blank=True, choices=[('food', 'Food'), ('toy', 'Toy'), ('accessory', 'Accessory')], help_text='Only for the "items bought (category)" metric.', max_length=10)),
                ('reward_coins', models.PositiveIntegerField(default=0, help_text='Bonus coins granted on unlock.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rarity', 'metric', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='UnlockedAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
    ]
