# Generated by Django 6.0.6 on 2026-07-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Only for the "items bought (specific item)" metric.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='unlockedachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='achievements.achievement'),
        ),
        migrations.AddField(
            model_name='unlockedachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='unlockedachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
