# Generated by Django 6.0.6 on 2026-07-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('ginger', 'Ginger'), ('grey', 'Grey'), ('black', 'Black'), ('white', 'White'), ('cream', 'Cream'), ('pink', 'Pink')], default='ginger', max_length=10),
        ),
        migrations.AddField(
            model_name='cat',
            name='configured',
            field=models.BooleanField(default=False),
        ),
    ]
