# Generated by Django 6.0.6 on 2026-07-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_achievement_player_last_active_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['rarity', 'metric', 'threshold']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Only for the "items bought (specific item)" metric.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.shopitem'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='purchases_by_item',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='metric',
            field=models.CharField(choices=[('login_streak', 'Login streak (consecutive days)'), ('tasks_done', 'Tasks completed'), ('tasks_failed', 'Tasks failed'), ('cat_happiness', 'Cat happiness reached (%)'), ('cat_satiety', 'Cat fullness reached (%)'), ('items_bought_total', 'Items bought (total)'), ('items_bought_category', 'Items bought (category)'), ('items_bought_item', 'Items bought (specific item)')], max_length=24),
        ),
    ]
