# Generated by Django 6.0.6 on 2026-07-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_achievement_options_achievement_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('orange', 'Orange'), ('grey', 'Grey'), ('black', 'Black'), ('white', 'White'), ('cream', 'Cream'), ('pink', 'Pink')], default='orange', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=15),
        ),
    ]
