# Generated by Django 6.0.6 on 2026-07-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('food', 'Food'), ('toy', 'Toy'), ('accessory', 'Accessory')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('icon', models.CharField(default='🎁', help_text='emoji shown in shop', max_length=8)),
                ('happiness_boost', models.FloatField(default=0)),
                ('satiety_boost', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=140)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort', 'price'],
            },
        ),
        migrations.CreateModel(
            name='OwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned', to='shop.shopitem')),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
