# Generated by Django 6.0.6 on 2026-07-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('deadline', models.DateTimeField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6)),
                ('estimated_pomodoros', models.PositiveSmallIntegerField(default=1)),
                ('completed_pomodoros', models.PositiveSmallIntegerField(default=0)),
                ('reward', models.PositiveIntegerField(default=20)),
                ('penalty', models.PositiveIntegerField(default=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('done', 'Done'), ('failed', 'Failed')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'deadline'],
            },
        ),
    ]
