# Generated by Django 6.0.6 on 2026-07-04 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Miso', max_length=40)),
                ('color', models.CharField(choices=[('orange', 'Orange'), ('grey', 'Grey'), ('black', 'Black'), ('white', 'White'), ('cream', 'Cream'), ('pink', 'Pink')], default='orange', max_length=10)),
                ('configured', models.BooleanField(default=False)),
                ('happiness', models.FloatField(default=70)),
                ('satiety', models.FloatField(default=70)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
